"""Generate individually reviewed reload parts; source geometry stays authoritative.

Selections, source fingerprints and the single shallow magazine cut are explicit
in reload_parts.json. No runtime bounding-box guess chooses a weapon's magazine.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import defaultdict
from pathlib import Path

from convert import ConversionError, validate_obj
from reload_mesh_audit import ROOT, read_obj


def sub(a, b):
    return tuple(x - y for x, y in zip(a, b))


def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


def area(triangle):
    normal = cross(sub(triangle[1][0], triangle[0][0]), sub(triangle[2][0], triangle[0][0]))
    return math.sqrt(sum(n*n for n in normal)) / 2


def clipped(polygon, height, below):
    result = []
    for a, b in zip(polygon, polygon[1:] + polygon[:1]):
        da, db = a[0][1] - height, b[0][1] - height
        inside_a, inside_b = (da <= 0, db <= 0) if below else (da >= 0, db >= 0)
        if inside_a:
            result.append(a)
        if inside_a != inside_b:
            t = da / (da - db)
            corner = tuple(tuple(x + (y-x)*t for x, y in zip(first, second)) for first, second in zip(a, b))
            length = math.sqrt(sum(x*x for x in corner[2]))
            result.append((corner[0], corner[1], tuple(x/length for x in corner[2])))
    return result


def triangulate(material, polygon):
    return [(material, [polygon[0], polygon[i], polygon[i+1]]) for i in range(1, len(polygon)-1)
            if area([polygon[0], polygon[i], polygon[i+1]]) > 1e-12]


def cap_boundaries(faces):
    edges = defaultdict(list)
    def key(corner):
        return tuple(round(x, 6) for x in corner[0])
    for material, triangle in faces:
        for a, b in zip(triangle, triangle[1:] + triangle[:1]):
            edges[tuple(sorted((key(a), key(b))))].append((material, a, b))
    boundary = [values[0] for values in edges.values() if len(values) == 1]
    caps = []
    while boundary:
        material, a, b = boundary.pop()
        loop = [a, b]
        while key(loop[-1]) != key(loop[0]):
            following = next((i for i, (_, start, _) in enumerate(boundary) if key(start) == key(loop[-1])), None)
            if following is None:
                break
            _, _, end = boundary.pop(following)
            loop.append(end)
        if key(loop[-1]) != key(loop[0]) or len(loop) < 4:
            continue
        loop = list(reversed(loop[:-1]))
        center = tuple(sum(c[0][axis] for c in loop)/len(loop) for axis in range(3))
        normal = [0.0, 0.0, 0.0]
        for a, b in zip(loop, loop[1:] + loop[:1]):
            contribution = cross(sub(a[0], center), sub(b[0], center))
            normal = [x+y for x, y in zip(normal, contribution)]
        length = math.sqrt(sum(x*x for x in normal))
        if length < 1e-10:
            continue
        normal = tuple(x/length for x in normal)
        uv = loop[0][1]
        for a, b in zip(loop, loop[1:] + loop[:1]):
            caps.extend(triangulate(material, [(center, uv, normal), (a[0], uv, normal), (b[0], uv, normal)]))
    return caps


def serialize(key, name, faces):
    lines = ["# Generated by tools/yaml_mesh_converter/split_reload_parts.py", f"mtllib {key}.mtl", f"o {name}"]
    for _, triangle in faces:
        for corner in triangle:
            for kind, values in zip(("v", "vt", "vn"), corner):
                lines.append(kind + " " + " ".join(f"{value:.12g}" for value in values))
    current = None
    for i, (material, _) in enumerate(faces):
        if current != material:
            lines.append("usemtl " + material)
            current = material
        lines.append("f " + " ".join(f"{j}/{j}/{j}" for j in range(i*3+1, i*3+4)))
    return "\n".join(lines) + "\n"


def generate(key, entry):
    source = ROOT / f"assets/models/weapons/{key}.obj"
    digest = hashlib.sha256(source.read_text(encoding="utf-8").encode()).hexdigest()
    if digest != entry["source_sha256"]:
        raise ConversionError(f"{key}: source changed; review the individual part selection")
    records, source_faces = read_obj(source)
    values = {kind: [tuple(map(float, line.split()[1:])) for line in lines] for kind, lines in records.items()}
    body, part = [], []
    selected = set(entry["faces"])
    if not selected or min(selected) < 0 or max(selected) >= len(source_faces):
        raise ConversionError(f"{key}: invalid part selection")
    original_area = 0.0
    for index, (material, face) in enumerate(source_faces):
        polygon = [tuple(values[kind][corner[channel]-1] for channel, kind in enumerate(("v", "vt", "vn"))) for corner in face]
        original_area += area(polygon)
        if index not in selected:
            body.extend(triangulate(material, polygon))
        elif "cut_y" in entry:
            part.extend(triangulate(material, clipped(polygon, entry["cut_y"], True)))
            body.extend(triangulate(material, clipped(polygon, entry["cut_y"], False)))
        else:
            part.extend(triangulate(material, polygon))
    reconstructed_area = sum(area(t) for _, t in body + part)
    if abs(reconstructed_area - original_area) > 1e-8:
        raise ConversionError(f"{key}: split changed source surface area")
    caps = cap_boundaries(part)
    report = {"source_faces": len(source_faces), "body_faces": len(body), "part_faces": len(part), "cap_faces": len(caps), "area_error": abs(reconstructed_area-original_area)}
    return {key+"_body": serialize(key, key+"_body", body), key+"_reload": serialize(key, key+"_reload", part+caps)}, report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    selections = json.loads(Path(__file__).with_name("reload_parts.json").read_text(encoding="utf-8"))
    reports = {}
    for key, entry in selections.items():
        # Even a shell port becomes stale when its receiver model changes.
        source = ROOT / f"assets/models/weapons/{key}.obj"
        digest = hashlib.sha256(source.read_text(encoding="utf-8").encode()).hexdigest()
        if digest != entry["source_sha256"]:
            raise ConversionError(f"{key}: source changed; review the loading part/port")
        if "faces" not in entry:
            continue
        outputs, reports[key] = generate(key, entry)
        for name, text in outputs.items():
            path = ROOT / f"assets/models/weapons/{name}.obj"
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != text:
                    raise ConversionError(f"{name}: missing or stale generated part")
            else:
                path.write_text(text, encoding="utf-8", newline="\n")
            validate_obj(path)
    print(json.dumps(reports, indent=2))
    print("RELOAD_PARTS_CHECK_PASS" if args.check else "RELOAD_PARTS_GENERATED")


if __name__ == "__main__":
    main()
