#!/usr/bin/env python3
"""Reproduce FR28a body/magazine meshes from the verified restored gun00.obj.

Run from any directory: python tools/yaml_mesh_converter/split_fr28a.py
Use --check to check the generated assets without writing them.

The magazine is joined to the receiver in the recovered mesh. Its ten authored
triangles are selected explicitly, never by a runtime position threshold. The
original coordinates, UVs, normals, and material are retained; both output meshes
therefore use the original gun's transform and normalization factor.

Two triangles close the detached magazine's existing top boundary. They use a
flat normal and an existing dark shell UV sample, without changing its outline.
The body keeps the actual magazine opening rather than inventing new geometry.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

from convert import ConversionError, validate_obj


SOURCE_SHA256 = "6a3e13be8d5f155ee860d379e5ff2b1cd5d483459c4747e6e36ab3320ebce531"
# Zero-based source triangle IDs, verified against the forward lower silhouette.
MAGAZINE_FACES = frozenset((24, 25, 64, 65, 66, 67, 68, 69, 102, 103))
# OBJ indices are one-based. Winding faces up into the receiver.
MAGAZINE_CAP = ((25, 121, 122), (25, 122, 26))
CAP_UV = 25
MATERIAL = "FR28A-Newlambert2"

Face = tuple[tuple[int, int, int], ...]


def read_source(path: Path) -> tuple[dict[str, list[str]], list[Face]]:
    # Text-mode newlines make this fingerprint independent of checkout EOLs.
    source_text = path.read_text(encoding="utf-8")
    actual_hash = hashlib.sha256(source_text.encode("utf-8")).hexdigest()
    if actual_hash != SOURCE_SHA256:
        raise ConversionError(
            f"{path}: source geometry changed ({actual_hash}); "
            "review the magazine face selection before regenerating"
        )
    records: dict[str, list[str]] = {"v": [], "vt": [], "vn": []}
    faces: list[Face] = []
    for line in source_text.splitlines():
        fields = line.split()
        if not fields:
            continue
        kind = fields[0]
        if kind in records:
            records[kind].append(line)
        elif kind == "f":
            faces.append(tuple(tuple(map(int, token.split("/"))) for token in fields[1:]))
    if len(faces) != 200 or any(len(records[kind]) != 246 for kind in records):
        raise ConversionError(f"{path}: unexpected source layout")
    return records, faces


def magazine_cap_normal(records: dict[str, list[str]]) -> str:
    points = [tuple(map(float, records["v"][index - 1].split()[1:])) for index in MAGAZINE_CAP[0]]
    ab = tuple(points[1][axis] - points[0][axis] for axis in range(3))
    ac = tuple(points[2][axis] - points[0][axis] for axis in range(3))
    normal = (
        ab[1] * ac[2] - ab[2] * ac[1],
        ab[2] * ac[0] - ab[0] * ac[2],
        ab[0] * ac[1] - ab[1] * ac[0],
    )
    length = math.sqrt(sum(component * component for component in normal))
    return "vn " + " ".join(f"{component / length:.12g}" for component in normal)


def build_part(records: dict[str, list[str]], source_faces: list[Face], magazine: bool) -> str:
    part_name = "gun00_magazine" if magazine else "gun00_body"
    part_records = {kind: values.copy() for kind, values in records.items()}
    faces = [face for index, face in enumerate(source_faces) if (index in MAGAZINE_FACES) == magazine]
    source_face_count = len(faces)
    if magazine:
        part_records["vn"].append(magazine_cap_normal(records))
        cap_normal_index = len(part_records["vn"])
        faces.extend(tuple((vertex, CAP_UV, cap_normal_index) for vertex in triangle) for triangle in MAGAZINE_CAP)

    lines = [
        "# Generated by tools/yaml_mesh_converter/split_fr28a.py; do not hand-edit.",
        f"# Source gun00.obj normalized SHA256: {SOURCE_SHA256}",
        "# Original coordinates, UVs, normals and material; no centering or scaling.",
        "mtllib gun00.mtl",
        "",
        f"o {part_name}",
    ]
    index_maps: list[dict[int, int]] = []
    # Drop unused records so the imported part AABB describes only that part.
    # Copy each retained source record verbatim; only face indices change.
    for channel, kind in enumerate(("v", "vt", "vn")):
        used = sorted({corner[channel] for face in faces for corner in face})
        index_maps.append({old: new for new, old in enumerate(used, 1)})
        lines.extend(part_records[kind][index - 1] for index in used)
    lines.extend(("", f"g material_{MATERIAL}", f"usemtl {MATERIAL}"))
    for index, face in enumerate(faces):
        if index == source_face_count:
            lines.append("# Magazine top cap: original four boundary corners, dark shell UV sample.")
        corners = ["/".join(str(index_maps[channel][corner[channel]]) for channel in range(3)) for corner in face]
        lines.append("f " + " ".join(corners))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify assets match the source without writing")
    args = parser.parse_args()
    directory = Path(__file__).resolve().parents[2] / "assets" / "models" / "weapons"
    records, faces = read_source(directory / "gun00.obj")
    results = {}
    for magazine in (False, True):
        name = "gun00_magazine" if magazine else "gun00_body"
        path = directory / f"{name}.obj"
        generated = build_part(records, faces, magazine)
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != generated:
                raise ConversionError(f"{path}: generated asset is missing or stale")
        else:
            path.write_text(generated, encoding="utf-8", newline="\n")
        results[name] = validate_obj(path)
    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
