#!/usr/bin/env python3
"""Split the authored RPG-21 warhead from its tube without changing geometry.

Run with --check to verify the generated OBJ files. Both pieces retain the
original coordinates, UVs, normals and material, and share gun11's scale.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from convert import ConversionError, validate_obj

SOURCE_SHA256 = "ef2de0f279b00787eec1c7d64c2ec53dfb6166865964f04f1c713560be49f6dd"
# The complete front warhead, including its existing rear cap; verified against
# the original OBJ's separate nose components. The tube and sight stay intact.
ROCKET_FACES = frozenset(range(52, 100))
# This zero-area source triangle does not render; omit it from the generated body.
DEGENERATE_FACES = frozenset((174,))


def generate(source: Path) -> dict[str, str]:
    text = source.read_text(encoding="utf-8")
    if hashlib.sha256(text.encode()).hexdigest() != SOURCE_SHA256:
        raise ConversionError("gun11 geometry changed; review the warhead selection")
    records: dict[str, list[str]] = {"v": [], "vt": [], "vn": []}
    faces: list[tuple[tuple[int, ...], ...]] = []
    for line in text.splitlines():
        fields = line.split()
        if not fields:
            continue
        if fields[0] in records:
            records[fields[0]].append(line)
        elif fields[0] == "f":
            faces.append(tuple(tuple(map(int, c.split("/"))) for c in fields[1:]))
    if len(faces) != 270:
        raise ConversionError("Unexpected RPG-21 triangle count")
    results = {}
    for rocket in (False, True):
        name = "gun11_rocket" if rocket else "gun11_body"
        selected = [f for i, f in enumerate(faces) if (i in ROCKET_FACES) == rocket and i not in DEGENERATE_FACES]
        lines = ["# Generated by tools/yaml_mesh_converter/split_rpg21.py",
                 "# Original coordinates, UVs, normals and materials.",
                 "mtllib gun11.mtl", "", "o " + name]
        maps = []
        for channel, kind in enumerate(("v", "vt", "vn")):
            used = sorted({corner[channel] for face in selected for corner in face})
            maps.append({old: new for new, old in enumerate(used, 1)})
            lines.extend(records[kind][index - 1] for index in used)
        lines.extend(("", "usemtl gun0910"))
        for face in selected:
            lines.append("f " + " ".join("/".join(str(maps[c][corner[c]]) for c in range(3)) for corner in face))
        results[name] = "\n".join(lines) + "\n"
    return results


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    directory = Path(__file__).resolve().parents[2] / "assets/models/weapons"
    results = {}
    for name, text in generate(directory / "gun11.obj").items():
        path = directory / (name + ".obj")
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                raise ConversionError(f"{path}: missing or stale generated mesh")
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
        results[name] = validate_obj(path)
    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
