# Generated by tools/build_reload_catalog.py from individually reviewed model selections.
extends RefCounted

const MODELS := {
	"gun00": {
		"category": "rifle",
		"part_label": "前下方細彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 30,
		"duration": 1.55,
		"bonus": 0.22
	},
	"gun01": {
		"category": "rifle",
		"part_label": "前下方斜置彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 30,
		"duration": 1.65,
		"bonus": 0.22
	},
	"gun02": {
		"category": "rifle",
		"part_label": "前下方短斜彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 32,
		"duration": 1.6,
		"bonus": 0.22
	},
	"gun03": {
		"category": "rifle",
		"part_label": "前置寬斜彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 30,
		"duration": 1.72,
		"bonus": 0.22
	},
	"gun04": {
		"category": "rifle",
		"part_label": "前下方嵌入式供彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "原科幻模型未標明供彈機構；以此原有部件設計可拆供彈艙，屬本次動畫設計。",
		"capacity": 36,
		"duration": 1.84,
		"bonus": 0.22
	},
	"gun05": {
		"category": "rifle",
		"part_label": "前下方弧形供彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "原科幻模型未標明供彈機構；以此原有部件設計可拆供彈艙，屬本次動畫設計。",
		"capacity": 40,
		"duration": 1.92,
		"bonus": 0.22
	},
	"gun06": {
		"category": "shotgun",
		"part_label": "槍身左下裝填口／逐顆彈殼",
		"variant_count": 2,
		"port": [
			-0.046,
			0.09,
			-0.08
		],
		"shell_radius": 0.018,
		"shell_length": 0.085,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "依機匣外形定位裝填口與彈殼尺寸；原模型未提供可動膛蓋。",
		"capacity": 6,
		"duration": 0.68,
		"bonus": 0
	},
	"gun07": {
		"category": "shotgun",
		"part_label": "機匣左側裝填口／逐顆彈殼",
		"variant_count": 2,
		"port": [
			-0.031,
			0.13,
			-0.12
		],
		"shell_radius": 0.015,
		"shell_length": 0.079,
		"outward": [
			-1,
			0,
			0
		],
		"design_note": "依機匣外形定位裝填口與彈殼尺寸；原模型未提供可動膛蓋。",
		"capacity": 8,
		"duration": 0.64,
		"bonus": 0
	},
	"gun08": {
		"category": "shotgun",
		"part_label": "扳機前側裝填口／逐顆彈殼",
		"variant_count": 2,
		"port": [
			-0.036,
			0.115,
			-0.15
		],
		"shell_radius": 0.014,
		"shell_length": 0.073,
		"outward": [
			-1,
			-0.3,
			0
		],
		"design_note": "依機匣外形定位裝填口與彈殼尺寸；原模型未提供可動膛蓋。",
		"capacity": 6,
		"duration": 0.62,
		"bonus": 0
	},
	"gun09": {
		"category": "shotgun",
		"part_label": "機匣側邊裝填口／逐顆彈殼",
		"variant_count": 2,
		"port": [
			-0.048,
			0.1,
			-0.08
		],
		"shell_radius": 0.019,
		"shell_length": 0.095,
		"outward": [
			-0.6,
			-0.8,
			0
		],
		"design_note": "依機匣外形定位裝填口與彈殼尺寸；原模型未提供可動膛蓋。",
		"capacity": 6,
		"duration": 0.74,
		"bonus": 0
	},
	"gun10": {
		"category": "shotgun",
		"part_label": "槍身左下裝填口／逐顆彈殼",
		"variant_count": 2,
		"port": [
			-0.042,
			0.1,
			-0.12
		],
		"shell_radius": 0.017,
		"shell_length": 0.081,
		"outward": [
			-0.4,
			-0.9,
			0
		],
		"design_note": "依機匣外形定位裝填口與彈殼尺寸；原模型未提供可動膛蓋。",
		"capacity": 8,
		"duration": 0.7,
		"bonus": 0
	},
	"gun11": {
		"category": "rocket",
		"part_label": "原 RPG-21 前端彈頭",
		"variant_count": 2,
		"outward": [
			0,
			0,
			-1
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 1,
		"duration": 2.42,
		"bonus": 0
	},
	"gun12": {
		"category": "rocket",
		"part_label": "原 RPG-24 細長彈頭",
		"variant_count": 2,
		"outward": [
			0,
			0,
			-1
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 1,
		"duration": 2.52,
		"bonus": 0
	},
	"gun13": {
		"category": "rocket",
		"part_label": "原 RPG-31 短錐彈頭",
		"variant_count": 2,
		"outward": [
			0,
			0,
			-1
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 1,
		"duration": 2.6,
		"bonus": 0
	},
	"gun14": {
		"category": "grenade",
		"part_label": "中央圓柱彈鼓與前後環",
		"variant_count": 2,
		"outward": [
			-1,
			0,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 4,
		"duration": 2.05,
		"bonus": 0.18
	},
	"gun15": {
		"category": "grenade",
		"part_label": "寬型中央彈鼓與前後環",
		"variant_count": 2,
		"outward": [
			-1,
			0,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 6,
		"duration": 2.24,
		"bonus": 0.18
	},
	"gun16": {
		"category": "grenade",
		"part_label": "上置圓柱彈鼓",
		"variant_count": 2,
		"outward": [
			-1,
			0,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 6,
		"duration": 2.32,
		"bonus": 0.18
	},
	"gun30": {
		"category": "rocket",
		"part_label": "後上方火箭供彈艙",
		"variant_count": 2,
		"outward": [
			0,
			1,
			0
		],
		"model_offset": [
			-0.042,
			0,
			-2.3
		],
		"design_note": "原科幻模型未標明供彈機構；以此原有部件設計可拆供彈艙，屬本次動畫設計。",
		"capacity": 1,
		"duration": 2.48,
		"bonus": 0
	},
	"gun34": {
		"category": "sniper",
		"part_label": "前下方長形供彈匣",
		"variant_count": 2,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "原科幻模型未標明供彈機構；以此原有部件設計可拆供彈艙，屬本次動畫設計。",
		"capacity": 5,
		"duration": 2.24,
		"bonus": 0.3
	},
	"gun35": {
		"category": "sniper",
		"part_label": "機匣前下方淺型彈倉匣",
		"variant_count": 2,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "原模型彈倉與機匣共面；沿底部輪廓分割淺型彈倉，保留上方機匣。",
		"capacity": 5,
		"duration": 2.18,
		"bonus": 0.3
	},
	"gun40": {
		"category": "rifle",
		"part_label": "前下方異形彈匣",
		"variant_count": 3,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 36,
		"duration": 1.88,
		"bonus": 0.22
	},
	"gun41": {
		"category": "grenade",
		"part_label": "右側圓形供彈模組",
		"variant_count": 2,
		"outward": [
			1,
			0,
			0
		],
		"authored_rotation": [
			-90,
			0,
			0
		],
		"design_note": "原科幻模型未標明供彈機構；以此原有部件設計可拆供彈艙，屬本次動畫設計。",
		"wrist_offset": [
			-0.07,
			0,
			0
		],
		"capacity": 4,
		"duration": 2.26,
		"bonus": 0.18
	},
	"gun43": {
		"category": "sniper",
		"part_label": "前下方楔形供彈匣",
		"variant_count": 2,
		"outward": [
			0,
			-1,
			0
		],
		"design_note": "保留原模型可辨識部件的輪廓、UV、材質與插槽座標。",
		"capacity": 5,
		"duration": 2.3,
		"bonus": 0.3
	},
	"gun45": {
		"category": "grenade",
		"part_label": "左側方形供彈艙",
		"variant_count": 2,
		"outward": [
			-1,
			0,
			0
		],
		"authored_rotation": [
			-90,
			0,
			0
		],
		"design_note": "原科幻模型未標明供彈機構；以此原有部件設計可拆供彈艙，屬本次動畫設計。",
		"capacity": 5,
		"duration": 2.4,
		"bonus": 0.18
	}
}

static func build() -> Dictionary:
	var profiles: Dictionary = {}
	for key: String in MODELS:
		var model: Dictionary = MODELS[key]
		var category := str(model.category)
		var shell := category == "shotgun"
		var rocket := key in ["gun11", "gun12", "gun13"]
		var style := "shotgun_shell" if shell else "rocket" if rocket else "grenade_drum" if category == "grenade" else "sniper" if category == "sniper" else "rifle"
		var profile := {
			"resource_model": "magazine", "magazine_size": int(model.capacity),
			"reload_style": style, "reload_time": float(model.duration), "empty_reload_bonus": float(model.bonus),
			"reload_category": category, "reload_variants": int(model.variant_count), "reload_part_label": model.part_label,
			"reload_design_note": model.design_note, "consume_reload_part": rocket,
			"drop_fraction": -1.0 if shell or rocket else 0.22,
			"hand_fraction": 0.18 if shell else 0.30 if rocket else 0.38,
			"insert_fraction": 0.82 if shell or rocket else 0.76,
			"reload_outward": _vector(model.outward),
			"reload_pull_distance": 0.16 if rocket else 0.14,
			"reload_model_offset": _vector(model.get("model_offset", [0, 0, 0])),
			"reload_wrist_offset": _vector(model.get("wrist_offset", [0, 0, 0])),
		}
		if model.has("authored_rotation"):
			profile["model_rotation"] = _vector(model.authored_rotation)
		if model.has("port"):
			profile["reload_port"] = _vector(model.port)
			profile["prop_shape"] = "shell"
			profile["prop_size"] = Vector3(float(model.shell_radius), float(model.shell_length), float(model.shell_radius))
			profile["prop_rotation"] = Vector3(90, 0, 0)
		else:
			profile["reload_body_model"] = key + "_body"
			profile["prop_model"] = key + "_reload"
		if key == "gun00":
			profile["prop_model"] = "gun00_magazine"
			profile["insert_fraction"] = 0.73
		if key == "gun11":
			profile["prop_model"] = "gun11_rocket"
		profiles[key] = profile
	return profiles

static func _vector(values: Array) -> Vector3:
	return Vector3(float(values[0]), float(values[1]), float(values[2]))
