"""Recover SW1 store coordinates; no raster resampling or layout inference.

python tools/ui_extractor/extract_mobile_store_layout.py --assets-root E:/Star-Warfare-1.0.2/Assets
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from extract_stage_icons import Reader, load_data, read_ui_offsets, read_unit_ui


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assets-root", type=Path, required=True)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    source = args.assets_root / "Resources/ui"
    data = (source / "resUI.bytes").read_bytes()
    offsets = read_ui_offsets(source / "res.bytes")
    units = {}
    for index in (11, 13, 19):
        unit = read_unit_ui(data, offsets[index])
        assert unit["end"] == offsets[index + 1], f"UI {index} parse boundary"
        frames = []
        for anim in unit["anim"]:
            modules = []
            for module in unit["frames"][anim["frame"]]["modules"]:
                record = {"type": module["type"]}
                if module["type"] == 0:
                    image = unit["images"][module["index"]]
                    record.update(image)
                    w, h = image["rect"][2:]
                elif module["type"] == 1:
                    w, h = unit["rects"][module["index"]]["size"]
                else:
                    raise ValueError(f"Unsupported module {module}")
                x = anim["position"][0] + module["position"][0] + 480
                y = 320 + anim["position"][1] + module["position"][1] - h
                record["screen"] = [x, y, w, h]
                modules.append(record)
            frames.append(modules)
        units[str(index)] = frames
    reader = Reader((source / "res.bytes").read_bytes())
    header = reader.i32()
    reader.i16()
    load_data(reader, header >> 24, 5)
    reader.unicode()
    text_groups = load_data(reader, 0, 0)
    descriptions = [group.split("\n") for group in text_groups[:3]]
    digest = hashlib.sha256(data).hexdigest()
    # One module per line makes source coordinate diffs reviewable.
    serialized = "{\n" + ",\n".join(
        f'\t"{key}": [\n' + ",\n".join(
            "\t\t[\n" + ",\n".join("\t\t\t" + json.dumps(module) for module in frame) + "\n\t\t]"
            for frame in frames) + "\n\t]" for key, frames in units.items()) + "\n}"
    output = root / "scripts/ui/sw1_store_layout.gd"
    output.write_text(
        'extends RefCounted\n\n# Generated by tools/ui_extractor/extract_mobile_store_layout.py.\n'
        f'# Source resUI.bytes SHA-256: {digest}\n'
        '# Coordinates: Unity bottom-left -> Godot top-left, 960 x 640.\n' +
        ''.join('const ' + name + ' := ' + json.dumps(values, ensure_ascii=False) + '\n\n'
                for name, values in zip(("WEAPON_DESCRIPTIONS", "ARMOR_DESCRIPTIONS", "BAG_DESCRIPTIONS"), descriptions)) +
        'const UNITS := ' + serialized + '\n\n'
        'static func module(unit: int, index: int, frame := 0) -> Dictionary:\n'
        '\treturn UNITS[str(unit)][frame][index]\n\n'
        'static func rect(unit: int, index: int, frame := 0) -> Rect2:\n'
        '\tvar r: Array = module(unit, index, frame).screen\n'
        '\treturn Rect2(r[0], r[1], r[2], r[3])\n', encoding="utf-8")
    print(f"Recovered {len(units)} units -> {output}")


if __name__ == "__main__":
    main()
