"""Build the offline upgrade lookup from recovered source tables and Godot captures."""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

from extract_unity_tables import read_tables

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/equipment_upgrades_v1"
CAPTURES = ROOT / "test_output/equipment_upgrades"
SCREENSHOTS = (
    "desktop_weapon_quote", "desktop_weapon_lv2", "desktop_insufficient",
    "desktop_suit_quote", "mobile_weapon", "mobile_suit_quote",
    "mobile_suit_lv6", "mobile_max",
)


def source_data() -> dict:
    binary = ROOT / "assets/starwarfare_data/resDataSets_raw.bin"
    tables = [table.decoded_rows() for table in read_tables(binary)]
    upgrade = tables[18]
    weapons = []
    for index, row in enumerate(tables[13]):
        stages = []
        percent = 100
        for level, (cost_percent, damage_percent) in enumerate(upgrade):
            percent += damage_percent
            stages.append({"level": level + 1, "damage": round(row[1] * percent / 100, 4),
                           "credits": row[9] * cost_percent // 10000 * 100, "mithril": 0})
        weapons.append({"key": f"gun{index:02d}", "name": row[0], "stages": stages})
    mapped = json.loads((ROOT / "docs/reconstruction_v1/com/mapped_armor.json").read_text(encoding="utf-8"))
    suits = []
    for key, suit in mapped["armor_sets"].items():
        raw = suit["raw"]
        increments = [float(value) for value in raw["UpgradePropAddPer"].split(";")]
        cash = [int(value) for value in raw["BuyMoney"].split(";")]
        crystal = [int(value) for value in raw["BuyCrystal"].split(";")]
        stages = []
        for index in range(7):
            factor = 1 + sum(increments[:index + 1])
            stages.append({"level": index + 1, "hp": round(suit["hp"] * factor, 4),
                           "shield": round(suit["shield"] * factor, 4),
                           "credits": cash[index] if index else 0,
                           "mithril": crystal[index] if index else 0})
        suits.append({"key": key, "name": suit["name"], "stages": stages})
    return {"source_sha256": hashlib.sha256(binary.read_bytes()).hexdigest(),
            "sw1_table18": upgrade, "weapons": weapons, "suits": suits}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated data without requiring local captures")
    args = parser.parse_args()
    output = "// Generated by tools/build_equipment_upgrade_review.py\nwindow.upgrades = " + json.dumps(source_data(), ensure_ascii=False, indent=2) + ";\n"
    target = REPORT / "data.js"
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != output:
            raise SystemExit("STALE: docs/equipment_upgrades_v1/data.js")
        for name in SCREENSHOTS:
            if not (REPORT / f"{name}.png").is_file():
                raise SystemExit(f"Missing screenshot: {name}")
        print("UPGRADE_REVIEW_CHECK_PASS")
        return
    for filename, marker in [("equipment_upgrade_test", "EQUIPMENT_UPGRADE_PASS"),
                             ("equipment_upgrade_ui_test", "EQUIPMENT_UPGRADE_UI_PASS"),
                             ("capture", "EQUIPMENT_UPGRADE_UI_PASS")]:
        log = (CAPTURES / f"{filename}.log").read_text(encoding="utf-8-sig")
        if marker not in log or "SCRIPT ERROR" in log or "FAIL:" in log:
            raise SystemExit(f"Required successful verification missing: {filename}")
    REPORT.mkdir(parents=True, exist_ok=True)
    target.write_text(output, encoding="utf-8", newline="\n")
    for name in SCREENSHOTS:
        shutil.copyfile(CAPTURES / f"{name}.png", REPORT / f"{name}.png")
    print("UPGRADE_REVIEW_GENERATED weapons=47 suits=8 captures=8")


if __name__ == "__main__":
    main()
