"""Compile the reviewed per-model reload data into an export-safe Godot catalog."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

RUNTIME = '''
static func build() -> Dictionary:
	var profiles: Dictionary = {}
	for key: String in MODELS:
		var model: Dictionary = MODELS[key]
		var category := str(model.category)
		var shell := category == "shotgun"
		var rocket := key in ["gun11", "gun12", "gun13"]
		var style := "shotgun_shell" if shell else "rocket" if rocket else "grenade_drum" if category == "grenade" else "sniper" if category == "sniper" else "rifle"
		var profile := {
			"resource_model": "magazine", "magazine_size": int(model.capacity),
			"reload_style": style, "reload_time": float(model.duration), "empty_reload_bonus": float(model.bonus),
			"reload_category": category, "reload_variants": int(model.variant_count), "reload_part_label": model.part_label,
			"reload_design_note": model.design_note, "consume_reload_part": rocket,
			"drop_fraction": -1.0 if shell or rocket else 0.22,
			"hand_fraction": 0.18 if shell else 0.30 if rocket else 0.38,
			"insert_fraction": 0.82 if shell or rocket else 0.76,
			"reload_outward": _vector(model.outward),
			"reload_pull_distance": 0.16 if rocket else 0.14,
			"reload_model_offset": _vector(model.get("model_offset", [0, 0, 0])),
			"reload_wrist_offset": _vector(model.get("wrist_offset", [0, 0, 0])),
		}
		if model.has("authored_rotation"):
			profile["model_rotation"] = _vector(model.authored_rotation)
		if model.has("port"):
			profile["reload_port"] = _vector(model.port)
			profile["prop_shape"] = "shell"
			profile["prop_size"] = Vector3(float(model.shell_radius), float(model.shell_length), float(model.shell_radius))
			profile["prop_rotation"] = Vector3(90, 0, 0)
		else:
			profile["reload_body_model"] = key + "_body"
			profile["prop_model"] = key + "_reload"
		if key == "gun00":
			profile["prop_model"] = "gun00_magazine"
			profile["insert_fraction"] = 0.73
		if key == "gun11":
			profile["prop_model"] = "gun11_rocket"
		profiles[key] = profile
	return profiles

static func _vector(values: Array) -> Vector3:
	return Vector3(float(values[0]), float(values[1]), float(values[2]))
'''

def main() -> None:
    source = json.loads((ROOT / "tools/yaml_mesh_converter/reload_parts.json").read_text(encoding="utf-8"))
    capacities = {0:30,1:30,2:32,3:30,4:36,5:40,6:6,7:8,8:6,9:6,10:8,11:1,12:1,13:1,14:4,15:6,16:6,30:1,34:5,35:5,40:36,41:4,43:5,45:5}
    durations = {0:1.55,1:1.65,2:1.60,3:1.72,4:1.84,5:1.92,6:.68,7:.64,8:.62,9:.74,10:.70,11:2.42,12:2.52,13:2.60,14:2.05,15:2.24,16:2.32,30:2.48,34:2.24,35:2.18,40:1.88,41:2.26,43:2.30,45:2.40}
    models = {}
    for key, entry in source.items():
        model = {k:v for k,v in entry.items() if k not in ["source_sha256", "faces", "cut_y", "existing_parts"]}
        id = int(key[3:])
        model.update(capacity=capacities[id], duration=durations[id], bonus=0 if entry["category"] in ["shotgun","rocket"] else .30 if entry["category"]=="sniper" else .18 if entry["category"]=="grenade" else .22)
        models[key] = model
    code = "# Generated by tools/build_reload_catalog.py from individually reviewed model selections.\nextends RefCounted\n\nconst MODELS := " + json.dumps(models, ensure_ascii=False, indent="\t") + "\n" + RUNTIME
    (ROOT / "scripts/core/weapon_reload_catalog.gd").write_text(code, encoding="utf-8", newline="\n")
    print("RELOAD_CATALOG_GENERATED", len(models))

if __name__ == "__main__":
    main()
