"""Compile the supplied Unity database into reproducible Godot constants and an audit page.

The binary is authoritative. The accompanying CSV/JSON column labels are not:
weapon col 2 is cooldown * 100, col 8 is energy, monster col 5 is loot cash.
See docs/data/recovered_data_v1/README.md for original C# field provenance.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
from pathlib import Path

from extract_unity_tables import read_tables

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/starwarfare_data/resDataSets_raw.bin"
REPORT = ROOT / "docs/data/recovered_data_v1"
TABLES = {
    "MONSTER_ROWS": 0, "WEAPON_SOURCE_ROWS": 13, "ARMOR_ROWS": 14,
    "SET_BONUS_ROWS": 15, "PROP_ROWS": 16, "RANK_ROWS": 17, "WEAPON_UPGRADE_ROWS": 18,
    "SKILL_ROWS": 73, "WEAPON_BOOST_ROWS": 74, "DEFENCE_ROWS": 75,
}
SHAPES = {0: (15, 6), 13: (47, 16), 14: (109, 16), 15: (21, 8),
          16: (11, 13), 17: (12, 2), 18: (8, 2), 73: (44, 16),
          74: (8, 15), 75: (2, 15)}


def signed(value: int, bits: int = 8) -> int:
    return value - (1 << bits) if value >= 1 << (bits - 1) else value


def gd_array(name: str, rows: list) -> str:
    return f"const {name} := [\n" + "".join(
        "\t" + json.dumps(row, ensure_ascii=False) + ",\n" for row in rows
    ) + "]\n\n"


def table(title: str, columns: list[str], rows: list) -> str:
    esc = lambda value: html.escape(str(value))
    return f"<h2>{esc(title)}</h2><div class='scroll'><table><thead><tr>" + "".join(
        f"<th>{esc(column)}</th>" for column in columns
    ) + "</tr></thead><tbody>\n" + "\n".join(
        "<tr>" + "".join(f"<td>{esc(cell)}</td>" for cell in row) + "</tr>" for row in rows
    ) + "</tbody></table></div>"


def outputs() -> dict[Path, str]:
    decoded = read_tables(SOURCE)
    if len(decoded) != 76:
        raise ValueError(f"Expected 76 tables, got {len(decoded)}")
    data = [t.decoded_rows() for t in decoded]
    for index, (rows, columns) in SHAPES.items():
        if len(data[index]) != rows or any(len(row) != columns for row in data[index]):
            raise ValueError(f"Unexpected shape for table {index}")
    for monster in data[0]:
        if not 1 <= monster[3] <= 11 or not data[monster[3]]:
            raise ValueError(f"Missing attack table for {monster[0]}")
    weapons = [[i, r[0], float(r[1]), signed(r[2], 16) / 100, signed(r[8], 16),
                r[11], signed(r[4]) / 10, float(r[5]), r[13], r[14], r[15], r[9], r[10]]
               for i, r in enumerate(data[13])]
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    gd = ('# Generated by tools/update_recovered_game_data.py. Do not hand edit.\n'
          'extends RefCounted\n\n' + f'const SOURCE_SHA256 := "{digest}"\n\n')
    gd += gd_array("WEAPON_ROWS", weapons)
    for name, index in TABLES.items():
        gd += f"# Unity table {index}; signed bytes are decoded by the consuming catalog.\n"
        gd += gd_array(name, data[index])
    gd += gd_array("ATTACK_TABLES", data[1:12])

    page = '''<!doctype html><html lang="zh-Hant"><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>原版數據套用對照</title>
<style>body{font:16px/1.65 system-ui,sans-serif;background:#101925;color:#e8f0fa;max-width:1200px;margin:32px auto;padding:0 20px}h1,h2{color:#81d6ff}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}th,td{text-align:left;padding:8px 12px;border-bottom:1px solid #304355}th{background:#203248;white-space:nowrap}a{color:#81d6ff}code{overflow-wrap:anywhere}small{color:#b4c7d7}</style>
<h1>原版數據套用對照</h1>
<p>武器、裝甲、背包、套裝／技能與道具共用這份資料；傷害、價格、解鎖需求在遊戲和商店採用同一來源。換彈動作與彈匣容量沿用已完成的設定。</p>
<p>裝甲 HP、回血與技能恢復原單位，移除舊的 0.01 倍縮減。Viper 加初始背包為 1,400 HP；既有 100 點護盾另外計算。</p>
<p>怪物資料收錄 15 種，目前關卡已有的 4 種模型套用相應基礎數值。crawler → 工蟲、spitter → 蠍尾蟲、brute（舊內部名稱）→ 自爆蟲、boss → 龍；未新增其他怪物的 AI 或生成排程。現有 AI 的攻擊動作與近戰距離仍沿用復刻版設定。關卡及精英倍率另外計算。</p>
<p>經驗值會用於原版 12 級軍階門檻；保留既有關卡進度提供的階級下限。原始武器升級表與 54 張生成排程表已解出供查閱，此次不改造升級介面、原版子關卡流程或 Boss 狀態機。</p>
<p><strong>欄位修正：</strong>附件的 clip_capacity 實為射擊間隔 × 100；req_level 實為單發能量；怪物 score 實為金錢獎勵。下表依原程式欄位顯示。</p>
<p><a href="README.md">欄位來源與套用範圍</a> · <a href="tables.json">完整 76 張解碼表</a></p>'''
    page += f"<small>resDataSets_raw.bin SHA-256: <code>{digest}</code></small>"
    page += table("怪物基礎數據", ["ID", "名称", "HP", "移速", "攻擊表", "經驗", "金錢", "目前生成"],
                  [[i] + row + [{0: "crawler", 2: "spitter", 3: "brute", 10: "boss"}.get(i, "未生成")]
                   for i, row in enumerate(data[0])])
    page += table("武器", ["ID", "名称", "傷害", "射擊間隔（秒）", "能量", "解鎖階級（從 1 起）", "點數", "秘銀"],
                  [[r[0], r[1], r[2], r[3], r[4], r[8] + 1, r[11], r[12]] for r in weapons])
    page += table("裝甲與背包", ["原表 ID", "名称", "HP", "攻擊%", "速度加成", "金錢%", "經驗%", "階級", "點數", "秘銀"],
                  [[i, r[0], r[2], signed(r[3]), signed(r[4]) / 10, signed(r[5]), signed(r[6]), r[12] + 1, r[14], r[15]] for i, r in enumerate(data[14])])
    page += table("消耗品", ["ID", "名稱", "恢復 HP", "持續秒數", "點數", "秘銀"],
                  [[i, r[0], r[4], r[8], r[11], r[12]] for i, r in enumerate(data[16])])
    page += table("軍階", ["階級", "名稱", "累積經驗門檻"], [[i + 1] + r for i, r in enumerate(data[17])])
    # Keep each decoded row on one line so a reviewer can compare table values.
    audit_tables = []
    for t in decoded:
        record = json.dumps({"index": t.index, "offset": t.offset, "columns": len(t.formats)})
        audit_tables.append("    " + record[:-1] + ', "data": [\n' + ",\n".join(
            "      " + json.dumps(row, ensure_ascii=False) for row in data[t.index]
        ) + "\n    ]}")
    audit = '{\n  "source_sha256": "' + digest + '",\n  "tables": [\n' + ",\n".join(audit_tables) + "\n  ]\n}\n"
    return {
        ROOT / "scripts/core/recovered_game_data.gd": gd.rstrip() + "\n",
        REPORT / "index.html": page + "</html>\n",
        REPORT / "tables.json": audit,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when tracked generated files are stale")
    args = parser.parse_args()
    for path, expected in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                raise SystemExit(f"STALE: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    print("RECOVERED_DATA_CHECK_PASS" if args.check else "RECOVERED_DATA_GENERATED tables=76")


if __name__ == "__main__":
    main()
